-- Insert 7 Auth Users
INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at, role, confirmation_token, recovery_token, email_change_token_new, email_change) 
VALUES
  (gen_random_uuid(), 'riya.sharma@example.com', crypt('Password123!', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"gender": "female", "last_name": "Sharma", "first_name": "Riya", "date_of_birth": "1998-05-15"}', now(), now(), 'authenticated', '', '', '', ''),
  (gen_random_uuid(), 'anjali.gupta@example.com', crypt('Password123!', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"gender": "female", "last_name": "Gupta", "first_name": "Anjali", "date_of_birth": "1996-10-22"}', now(), now(), 'authenticated', '', '', '', ''),
  (gen_random_uuid(), 'sneha.patel@example.com', crypt('Password123!', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"gender": "female", "last_name": "Patel", "first_name": "Sneha", "date_of_birth": "1995-12-05"}', now(), now(), 'authenticated', '', '', '', ''),
  (gen_random_uuid(), 'priyanka.singh@example.com', crypt('Password123!', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"gender": "female", "last_name": "Singh", "first_name": "Priyanka", "date_of_birth": "1999-03-18"}', now(), now(), 'authenticated', '', '', '', ''),
  (gen_random_uuid(), 'rohit.verma@example.com', crypt('Password123!', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"gender": "male", "last_name": "Verma", "first_name": "Rohit", "date_of_birth": "1994-08-30"}', now(), now(), 'authenticated', '', '', '', ''),
  (gen_random_uuid(), 'amit.kumar@example.com', crypt('Password123!', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"gender": "male", "last_name": "Kumar", "first_name": "Amit", "date_of_birth": "1993-02-14"}', now(), now(), 'authenticated', '', '', '', ''),
  (gen_random_uuid(), 'karan.malhotra@example.com', crypt('Password123!', gen_salt('bf')), now(), '{"provider": "email", "providers": ["email"]}', '{"gender": "male", "last_name": "Malhotra", "first_name": "Karan", "date_of_birth": "1992-11-11"}', now(), now(), 'authenticated', '', '', '', '')
ON CONFLICT (email) DO NOTHING;

-- Insert the detailed profiles for the 7 new users
INSERT INTO public.profiles (user_id, first_name, last_name, gender, date_of_birth, religion_name, caste_name, manglik, profile_for, managed_by, degree, employed_in, occupation, annual_income, city, state, country, family_type, height, weight, marital_status, about_me, status)
VALUES
  ((SELECT id FROM auth.users WHERE email = 'riya.sharma@example.com'), 'Riya', 'Sharma', 'female', '1998-05-15', 'Hindu', 'Brahmin', 'No', 'Myself', 'Self', 'B.Tech', 'Private Sector', 'Software Engineer', 1200000, 'Delhi', 'Delhi', 'India', 'Nuclear', 165, 55, 'never_married', 'I am a software engineer working in a reputed MNC. I love traveling and reading.', 'approved'),
  ((SELECT id FROM auth.users WHERE email = 'anjali.gupta@example.com'), 'Anjali', 'Gupta', 'female', '1996-10-22', 'Hindu', 'Baniya', 'Yes', 'Daughter', 'Parent', 'MBA', 'Private Sector', 'HR Manager', 1500000, 'Mumbai', 'Maharashtra', 'India', 'Joint', 160, 58, 'never_married', 'Looking for a well-educated partner for my daughter who balances modern values with tradition.', 'approved'),
  ((SELECT id FROM auth.users WHERE email = 'sneha.patel@example.com'), 'Sneha', 'Patel', 'female', '1995-12-05', 'Hindu', 'Patel', 'No', 'Myself', 'Self', 'BDS', 'Self Employed', 'Dentist', 2000000, 'Ahmedabad', 'Gujarat', 'India', 'Nuclear', 162, 60, 'divorced', 'I am a practicing dentist with my own clinic. Looking for someone understanding and supportive.', 'pending'),
  ((SELECT id FROM auth.users WHERE email = 'priyanka.singh@example.com'), 'Priyanka', 'Singh', 'female', '1999-03-18', 'Hindu', 'Rajput', 'No', 'Sister', 'Sibling', 'MA Ecomomics', 'Government', 'Civil Servant', 900000, 'Jaipur', 'Rajasthan', 'India', 'Nuclear', 168, 56, 'never_married', 'Priyanka is a focused and ambitious girl. Seeking a partner with similar values.', 'approved'),
  ((SELECT id FROM auth.users WHERE email = 'rohit.verma@example.com'), 'Rohit', 'Verma', 'male', '1994-08-30', 'Hindu', 'Kayastha', 'No', 'Myself', 'Self', 'B.E.', 'Private Sector', 'Data Scientist', 2500000, 'Bangalore', 'Karnataka', 'India', 'Nuclear', 178, 75, 'never_married', 'Passionate about data and AI. I enjoy hiking and photography on weekends.', 'approved'),
  ((SELECT id FROM auth.users WHERE email = 'amit.kumar@example.com'), 'Amit', 'Kumar', 'male', '1993-02-14', 'Hindu', 'Yadav', 'No', 'Son', 'Parent', 'MD', 'Private Sector', 'Doctor', 3000000, 'Lucknow', 'Uttar Pradesh', 'India', 'Joint', 175, 80, 'never_married', 'We are seeking a suitable match for our son who is a practicing physician at a reputed hospital.', 'pending'),
  ((SELECT id FROM auth.users WHERE email = 'karan.malhotra@example.com'), 'Karan', 'Malhotra', 'male', '1992-11-11', 'Hindu', 'Khatri', 'Yes', 'Myself', 'Self', 'CA', 'Self Employed', 'Chartered Accountant', 4000000, 'Delhi', 'Delhi', 'India', 'Nuclear', 180, 78, 'never_married', 'Running my own CA firm. Looking for a modern, independent partner.', 'approved')
ON CONFLICT (user_id) DO UPDATE SET 
  religion_name = EXCLUDED.religion_name, caste_name = EXCLUDED.caste_name, manglik = EXCLUDED.manglik, profile_for = EXCLUDED.profile_for, 
  managed_by = EXCLUDED.managed_by, degree = EXCLUDED.degree, employed_in = EXCLUDED.employed_in, occupation = EXCLUDED.occupation, 
  annual_income = EXCLUDED.annual_income, city = EXCLUDED.city, state = EXCLUDED.state, country = EXCLUDED.country, 
  family_type = EXCLUDED.family_type, height = EXCLUDED.height, weight = EXCLUDED.weight, marital_status = EXCLUDED.marital_status::marital_status_enum, 
  about_me = EXCLUDED.about_me, status = EXCLUDED.status::profile_status_enum;
